export enum ProjectAliasesEnum {
  BathroomRemodeling = 'br',
  GutterGuards = 'gg',
  KitchenCabinets = 'kc',
  KitchenRemodeling = 'kr',
  Roofing = 'rf',
  Siding = 'sd',
  Stairlifts = 'sl',
  WalkInShowers = 'wis',
  WalkInTubs = 'wit',
  WindowsReplacement = 'wr',
  HVAC = 'hvac',
  Decks = 'dk',
  Landscaping = 'ls',
  BasementWaterproofing = 'bw',
  Flooring = 'fl',
  HeatPumps = 'hp',
  DrainSewerServices = 'dss',
  Electrical = 'el',
  HomeWarranty = 'hw',
  KitchenCabinetRefacing = 'kcr',
}
